/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR		0x40023800UL
#define RCC_CFGR_ENR_OFFSET 0x08UL
#define RCC_CFGR_ENR_ADDR 	(RCC_BASE_ADDR + RCC_CFGR_ENR_OFFSET)

int main(void)
{
	// Output MOx
	*((volatile uint32_t *) RCC_CFGR_ENR_ADDR) &= (0x03 << 21);
	// Enable clock GPIOA
	*((volatile uint32_t *) (RCC_BASE_ADDR + 0x30)) |= (1 << 0);
	// Configure mode GPIOA - pin 8 - alternate function


    /* Loop forever */
	for(;;);
}
