/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f407xx.h>
#include "software_delay.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void EXTI0_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_PIN_NO_0);
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
}

int main(void)
{
	GPIO_Handle_t button;
	GPIO_Handle_t LED;

	GPIO_Config(&LED, GPIOD, GPIO_PIN_NO_12, GPIO_MODE_OUT, GPIO_SPEED_FAST, GPIO_OP_TYPE_PP, GPIO_NO_PUPD, 0);
	GPIO_Config(&button, GPIOA, GPIO_PIN_NO_0, GPIO_MODE_IT_FT, GPIO_SPEED_FAST, GPIO_OP_TYPE_OD, GPIO_NO_PUPD, 0);

	GPIO_PeriClockControl(LED.pGPIOx, ENABLE);
	GPIO_PeriClockControl(button.pGPIOx, ENABLE);

	GPIO_Init(&button);
	GPIO_Init(&LED);

	// Interrupt config
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, ENABLE);
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI0, 0);

    /* Loop forever */
	while(1)
	{
		// DO NOTHING
	}
}
