/**
 ******************************************************************************
 * @file           : spi_tx_test.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f407xx.h>
#include "software_delay.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
/*
    PB14 (SPI2_MISO)
    PB15 (SPI2_MOSI)
    PB13 (SPI2_SCK)
    PA4  (SPI2_NSS)
*/
void SPI2_GPIO_Init(void)
{
    GPIO_Handle_t spiPIN;
    spiPIN.pGPIOx = GPIOB;
    spiPIN.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    spiPIN.GPIO_PinConfig.GPIO_PinAltFunMode = 5; // AF5 for SPI2
    spiPIN.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    spiPIN.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    spiPIN.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    // SCLK
    spiPIN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
    GPIO_Init(&spiPIN);

    // MOSI
    spiPIN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
    GPIO_Init(&spiPIN);

    // MISO
    // spiPIN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
    // GPIO_Init(&spiPIN);

    // NSS
    // spiPIN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
    // GPIO_Init(&spiPIN);
}

void SPI2_Init(SPI_Handle_t *pSPI2Handle)
{
    // Initialize SPI2 data
    pSPI2Handle->pSPIx = SPI2;
    pSPI2Handle->SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
    pSPI2Handle->SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FULLDUPLEX;
    pSPI2Handle->SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2;
    pSPI2Handle->SPIConfig.SPI_DFF = SPI_DFF_8BITS;
    pSPI2Handle->SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
    pSPI2Handle->SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
    pSPI2Handle->SPIConfig.SPI_SSM = SPI_SSM_EN;


    // Hardware initialization
    SPI_HWInit(pSPI2Handle);

}

int main(void)
{
    SPI_Handle_t *pSPI2Handle = calloc(1, sizeof(SPI_Handle_t));

    char user_data[] = "hello world";
    // Initialize GPIO and SPI for SPI2
	SPI2_GPIO_Init();

    SPI2_Init(pSPI2Handle);

    SPI_PeripheralControl(pSPI2Handle, ENABLE);

    SPI_SendData(pSPI2Handle, user_data, sizeof(user_data));

    /* Loop forever */
	while(1)
	{

	}
}
